# Generated by Django 3.0.1 on 2020-01-05 07:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.custom_upload_to, verbose_name='Imagen')),
                ('header', models.CharField(blank=True, max_length=150, verbose_name='Encabezado del cover')),
                ('paragraph', models.TextField(blank=True, verbose_name='Párrafor del cover')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name_plural': 'Cover',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.custom_upload_to, verbose_name='Imagen')),
                ('header', models.CharField(blank=True, max_length=150, verbose_name='Encabezado del footer')),
                ('paragraph', models.TextField(blank=True, verbose_name='Párrafo del footer')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título del post de la primera página', max_length=150, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Subtítulo')),
                ('paragraphTitle', models.CharField(blank=True, max_length=150, verbose_name='Título del párrafo')),
                ('content', models.TextField(verbose_name='Párrafo')),
                ('image', models.ImageField(blank=True, help_text='Imagen del post de la primera página', upload_to=core.models.index_upload_to, verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name_plural': 'Index',
            },
        ),
    ]
