# Generated by Django 3.0.1 on 2020-01-05 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, verbose_name='Tipo')),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10,10}$')], verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Teléfono',
            },
        ),
    ]
