# Generated by Django 3.0.1 on 2020-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('C', 'Casa'), ('O', 'Oficina')], max_length=1, verbose_name='Tipo'),
        ),
    ]
