# Generated by Django 3.0.1 on 2020-01-05 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200105_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10,10}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('C', 'Casa'), ('O', 'Oficina')], default=0, max_length=1, verbose_name='Tipo'),
        ),
    ]
