# Generated by Django 3.0.1 on 2020-01-05 09:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200105_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.logo_upload_to, verbose_name='Logo'),
        ),
    ]
