# Generated by Django 3.0.1 on 2020-01-05 09:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200105_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default='logo', max_length=10, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logo',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to=core.models.logo_upload_to, verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
