# Generated by Django 3.0.1 on 2020-01-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200105_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(default='Logo', max_length=10, verbose_name='Nombre'),
        ),
    ]
