# Generated by Django 3.0.1 on 2020-01-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200105_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
