# Generated by Django 3.0.1 on 2020-01-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Horario'},
        ),
    ]
